registration:
  methods: ['GET']
  path: /app/registration
  controller: bitbag.shopware_dpd_app.app_system.controller.registration_controller

confirm_registration:
  methods: ['POST']
  path: /app/registration/confirm
  controller: bitbag.shopware_dpd_app.app_system.controller.confirmation_controller

app_lifecycle:
  resource: './lifecycle_routes.yaml'
  prefix: /app/lifecycle
  methods: ['POST']
  name_prefix: app_lifecycle_

create_package:
  methods: ['POST']
  path: /app/create-package
  controller: bitbag.shopware_dpd_app.controller.create_package_action

get_label_pdf:
  methods: ['GET']
  path: /app/label/{orderId}
  controller: bitbag.shopware_dpd_app.controller.show_label_action

configuration_module_show:
  methods: ['GET', 'POST']
  path: /app/modules/configuration
  controller: bitbag.shopware_dpd_app.controller.configuration_module
